---
- hosts: idp-servers
  vars:
    sifulan_binaries:
      baseurl: https://raw.githubusercontent.com/sifulan-access-federation/shibboleth-binaries/3.4
    download:
      jetty:
        baseurl: "{{ sifulan_binaries.baseurl }}/jetty"
        version: 9.4.14.v20181114
        sha256sum: c66abd7323f6df5b28690e145d2ae829dbd12b8a2923266fa23ab5139a9303c5
      shib_idp:
        baseurl: "{{ sifulan_binaries.baseurl }}/shibboleth"
        version: 4.0.1
        sha256sum: 832f73568c5b74a616332258fd9dc555bb20d7dd9056c18dc0ccf52e9292102a
      mysql_connector:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/Connector-J"
        version: 8.0.13
        sha256sum: 99501fbc74b4cb80cd75a4d06c38b662be01bfd39c409efa3c747ec83216329b
      dta_ssl:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/jetty9-dta-ssl"
        version: 1.0.0
        sha256sum: 9c62a5999d5adddea905d7caf4220fc073e6033b755f224084cc240dc8d992a6
      commons_dbcp2:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/commons_dbcp2"
        version: 2.5.0
        sha256sum: 2e9da64b97af50951a3ac14b2269993fd8de323e00265d0e6a952fc108f05a22
      commons_pool2:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/commons_pool2"
        version: 2.6.0
        sha256sum: 961606add45d4212951482327d6b541214af1f95ea21b0528628eb031a4af522
      aaf_shib_ext:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/aaf_shib_ext"
        version: 1.1.1
        sha256sum: faf6de1f8be40ec3b3e9cab93ad8ee38a1de77dad51bef36358e28e8d6ae9116
      keystore:
        baseurl: "{{ sifulan_binaries.baseurl }}/keystore"
        version: "Unknown"
        sha256sum: ae4185b2f0bb1af00abc6a4502fbfbdc6a90aec65c7bcee08e37a1bc20de5ac1
      cas_client_core:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/cas_extensions"
        version: 3.4.1
        sha256sum: 840a860da8e1cd65bb2b66c38222518e87158edfe8c3dc5a94f6e1183511c445
      shib_cas_authenticator:
        baseurl: "{{ sifulan_binaries.baseurl }}/jars/cas_extensions"
        version: 3.2.3
        sha256sum: a21766ff6010f15177760d2cfc4409c81e068447ce1f62281586e5daf07c23a0
    urls:
      jetty:
        url: "{{ download.jetty.baseurl }}/jetty-distribution-{{ download.jetty.version }}.tar.gz"
      shib_idp:
        url: "{{ download.shib_idp.baseurl }}/shibboleth-identity-provider-{{ download.shib_idp.version }}.tar.gz"
      mysql_connector:
        url: "{{ download.mysql_connector.baseurl }}/mysql-connector-java-{{ download.mysql_connector.version }}.tar.gz"
      dta_ssl:
        url: "{{ download.dta_ssl.baseurl }}/jetty9-dta-ssl-{{download.dta_ssl.version}}.jar"
      commons_dbcp2:
        url: "{{ download.commons_dbcp2.baseurl }}/commons-dbcp2-{{ download.commons_dbcp2.version }}-bin.tar.gz"
      commons_pool2:
        url: "{{ download.commons_pool2.baseurl }}/commons-pool2-{{ download.commons_pool2.version }}-bin.tar.gz"
      aaf_shib_ext:
        url: "{{ download.aaf_shib_ext.baseurl }}/aaf-shib-ext-{{ download.aaf_shib_ext.version }}.jar"
      keystore:
        url: "{{ download.keystore.baseurl }}/keystore"
      cas_client_core:
        url: "{{ download.cas_client_core.baseurl }}/cas-client-core-{{ download.cas_client_core.version }}.jar"
      shib_cas_authenticator:
         url: "{{ download.shib_cas_authenticator.baseurl }}/shib-cas-authenticator-{{ download.shib_cas_authenticator.version }}.jar"
    installer:
      root: "{{ install_base }}/shibboleth-idp-installer"
      path: "{{ install_base }}/shibboleth-idp-installer/build"
      repository: "{{ install_base }}/shibboleth-idp-installer/repository"
    jetty:
      root: "{{ install_base }}/jetty"
      home: "{{ install_base }}/jetty/jetty-distribution-{{ download.jetty.version }}"
      base: "{{ install_base }}/shibboleth/jetty"
      current: "{{ install_base }}/jetty/current"
      tmp_directory: "{{ install_base }}/jetty/tmp"
      state_directory: "{{ install_base }}/jetty/tmp"
    shib_idp:
      home_root: "{{ install_base }}/shibboleth/shibboleth-idp"
      home: "{{ install_base }}/shibboleth/shibboleth-idp/shibboleth-idp-{{ download.shib_idp.version }}"
      libs: "{{ install_base }}/shibboleth/libs"
      src_root: "{{ install_base }}/shibboleth/shibboleth-src"
      src: "{{ install_base }}/shibboleth/shibboleth-src/shibboleth-identity-provider-{{ download.shib_idp.version }}"
      keystore_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/shib_idp_keystore chars=letters,digits length=64') }}"
      cookie_enc_key_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/cookie_enc_key chars=letters,digits length=64') }}"
      aepst_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/aespt_salt chars=letters,digits length=64') }}"
      targeted_id_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/targeted_id_salt chars=letters,digits length=64') }}"
    db:
      name: idp_db
      username: idp_admin
      password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
  tasks:
    - name: 'Create required directories for installer setup'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - '{{ installer.root }}'
        - '{{ installer.path }}'

    - name: 'Update yum packages (yum -y update)'
      yum: name=* state=latest
      when: ((server_patch is undefined) or (server_patch is none) or (server_patch=="true"))

    #- name: 'Set SELinux to permissive mode'
    #  selinux:
    #    policy: targeted
    #    state: permissive

    - name: 'Install required packages'
      yum:
        name:
          - httpd
          - mod_ssl
          - mod_ldap
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
          - mariadb-devel
          - mariadb
          - mariadb-server
          - MySQL-python
          - ntp
        state: installed

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include_tasks: tasks/jetty.yml
    - include_tasks: tasks/db.yml
    - include_tasks: tasks/idp.yml
    - include_tasks: tasks/apache.yml
    - include_tasks: tasks/firewalld.yml
      when: firewall is defined and firewall=="firewalld"
    - include_tasks: tasks/iptables.yml
      when: firewall is defined and firewall=="iptables"

  handlers:
    - name: Restart idp
      service:
        name: idp
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
